version: "3.8"

services:
  express:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - my_network
    volumes:
      - ./backend:/usr/src/backend
    env_file:
      - ./backend/.env
    command: sh -c "npx prisma migrate dev && npm run dev"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:13
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5050:80"

  react:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my_network
    volumes:
      - ./frontend/src:/usr/src/backend/src

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
