version: "3.8"

services:
  express:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    command: sh -c "npx prisma migrate dev && npm run dev"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:13
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5050:80"

  react:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

volumes:
  postgres_data:
